source 'http://rubygems.org'

gem 'celluloid'
gem 'reel-rack'
gem 'webmachine'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'rspec'
gem 'haml'
gem 'guard'
gem 'guard-rspec'
gem 'kubeclient', :git => "https://github.com/derfred/kubeclient.git", :branch => "namespace_support"
gem 'timeout-extensions'
gem 'activesupport'
gem 'activemodel'
